// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6aiEW_g_HNspnLQzGxLT2rmBPynDge_4',
    appId: '1:606321730491:web:c43c218443c7021d5dda9e',
    messagingSenderId: '606321730491',
    projectId: 'serviceflow-69ea6',
    authDomain: 'serviceflow-69ea6.firebaseapp.com',
    storageBucket: 'serviceflow-69ea6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqcafFeqOG6iOplp4dWZEH50yruuoWuRA',
    appId: '1:606321730491:android:b85ba5f78e8772695dda9e',
    messagingSenderId: '606321730491',
    projectId: 'serviceflow-69ea6',
    storageBucket: 'serviceflow-69ea6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2CrrUz8RMSMa5zRtu_9XerF5NABR91o',
    appId: '1:606321730491:ios:9822f696401986685dda9e',
    messagingSenderId: '606321730491',
    projectId: 'serviceflow-69ea6',
    storageBucket: 'serviceflow-69ea6.firebasestorage.app',
    iosBundleId: 'com.example.serviceflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe2CrrUz8RMSMa5zRtu_9XerF5NABR91o',
    appId: '1:606321730491:ios:9822f696401986685dda9e',
    messagingSenderId: '606321730491',
    projectId: 'serviceflow-69ea6',
    storageBucket: 'serviceflow-69ea6.firebasestorage.app',
    iosBundleId: 'com.example.serviceflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6aiEW_g_HNspnLQzGxLT2rmBPynDge_4',
    appId: '1:606321730491:web:fab67fe295caef145dda9e',
    messagingSenderId: '606321730491',
    projectId: 'serviceflow-69ea6',
    authDomain: 'serviceflow-69ea6.firebaseapp.com',
    storageBucket: 'serviceflow-69ea6.firebasestorage.app',
  );
}
